language: node_js
node_js:
- '5'
services:
  - redis-server
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: "31077d862d6ab8903b98d6adc3d4c39495d9a6a6312080ee6167d2ddaff847ad"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
