language: node_js
node_js:
- '5'
services:
  - redis-server
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: "f8e1f4ef5f480b36c7e021976ccefcae74f4644a2d67d3e0910e5f208acac9c3"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
